### ISSUE TITLE
Don't have write access

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.8#3]
How am I suppose to do awesome things if I can't push code!? :sob:

**Comment by Sunconure11** [comment]
It appears you are not a collaborator. I think you will need Ala to help you get that status.

**Comment by Sunconure11** [comment]
Plus, I think that after me and Pitch finish the next module idea, and then return to milk with a few more things (and maybe the wine racks somewhere in between), we should port to 1.8 at that time. 1.8 is becoming more relevant.

**Comment by Alatyami** [comment]
Should be good now ...

**Comment by Alatyami** [comment]
Highjacking this ticket a bit ... 

After there is a working BETA for GC-1.8 we should start to prepare GC-1.7 for maintenance.

**Comment by Sunconure11** [comment]
I think the 1.8 build should only be worked on after me and Pitch send our second wave of stuff for the milk module, which will likely be after the grain module. Or alternatively, after the grain module. Plus we have a few modules that are not finished at the moment, such as milk, and nether.
