### ISSUE TITLE
Permission to get dev access

### ISSUE THREAD

**Issue by gurugeek42** [GrowthcraftCE/Growthcraft-1.8#4]
Hey, I emailed Corey about getting access to 1.8 to start porting the existing codebase over. 
Could I be added to devs?

**Comment by gurugeek42** [comment]
Also, what's the status on this? Has any work been done on 1.8?

**Comment by Alatyami** [comment]
Sure thing ...

**Comment by Alatyami** [comment]
You've been added. We were waiting for some items to get resolved in the 1.7 codebase before heading over to 1.8. Corey has a restructure plan he wants to implement.
